name: "Hello Actions"
description: "Greet someone"
author: "mezgoodle"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}

branding:
  icon: "mic"
  color: "purple"
