name: "Hello Actions"
description: "Greet someone"
author: "mezgoodle"

inputs:
  GITHUB_TOKEN:
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}

branding:
  icon: "mic"
  color: "purple"
