name: Auto formate code
on: push

jobs:
  build:
    name: Main action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
