name: Auto formate code
on: push

jobs:
  build:
    name: Main action
    runs-on: ubuntu-latest
    steps:
      - uses: /checkout@v1
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
